apiVersion: apps/v1
kind: Deployment
metadata:
  name: pages-deployment
  labels:
    app: pages
spec:
  replicas: 2  # Vous pouvez ajuster le nombre de réplicas selon vos besoins
  selector:
    matchLabels:
      app: pages
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
        - name: pages
          image: wradgio/stretchshop:latest  # Remplacez par l'image correcte de votre service "cart"
          ports:
            - containerPort: 3000  # Assurez-vous que le port exposé correspond au port utilisé par votre service "cart"
          env:
            - name: SERVICES
              value: pages

---
apiVersion: v1
kind: Service
metadata:
  name: pages-service
spec:
  selector:
    app: pages
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Assurez-vous que le port cible correspond au port exposé dans le déploiement
  type: ClusterIP  # Vous pouvez utiliser un autre type de service selon vos besoins
