# Utiliser l'image officielle de NATS provenant de Docker Hub
FROM nats

# Définir l'entrée de commande personnalisée pour le serveur NATS
ENTRYPOINT ["/nats-server", "-D", "--user", "defaultUsername", "--pass", "defaultPassword"]

# Vous pouvez ajouter d'autres commandes spécifiques au service NATS si nécessaire
