# Utiliser l'image officielle de MongoDB provenant de Docker Hub
FROM mongo

# Copier les fichiers de configuration
COPY ./dbconf /etc/mongo

# Vous pouvez ajouter d'autres commandes spécifiques au service mongo si nécessaire
