apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 885801475464.dkr.ecr.eu-west-3.amazonaws.com/ecr_dev:api
          env:
            - name: SERVICES
              value: "api"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000