# Utiliser une image de base provenant de Docker Hub
FROM wradgio/stretchshop:latest

# Définir les variables d'environnement spécifiques pour ce service
ENV SERVICES=subscriptions

# Vous pouvez ajouter des commandes supplémentaires spécifiques au service si nécessaire

# Commande par défaut pour le service
CMD ["node", "app.js"]