name: "Build and push to EKS"

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  BuildAndPushImageToEKS:
    name: "Build and Push to EKS"
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3


      - name: Update kube config
        run: |
          aws eks update-kubeconfig --name eks_dev

      # Deploy the YAML files from the kubernetes folder
      - name: Deploy Kubernetes resources
        run: kubectl apply --recursive -f kubernetes