name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 885801475464.dkr.ecr.eu-west-3.amazonaws.com/ecr_dev
          region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ID_SANDBOX }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SANDBOX }}


      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: 885801475464.dkr.ecr.eu-west-3.amazonaws.com/ecr_dev
          IMAGE_NAME: my-image
          TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$TAG .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG